title: Custom Docker Image for Kotlin-based Applications
description: An open-source project that provides a Docker image designed for running Kotlin-based applications
show_downloads: false
theme: jekyll-theme-cayman
