version: '3'
services:
  kotlin:
    container_name: kotlin
    image: 'api.repoflow.io/desiderati/docker/library/kotlin:21'
    ports:
      # Uncomment the line below to enable remote debugging support.
      - '9091:8090'

      # Uncomment the line below to enable JMX Agent support.
      #- 9010:9010

    environment:
      # Run id -u ${USER} to find out the local user's ID.
      # Files generated in the mapped volumes will have the local user's permissions.
      - LOCAL_USER_ID=1000

      # Uncomment the line below to enable remote debugging support.
      - ENABLE_DEBUG=true

      # Uncomment the line below to enable JMX Agent support.
      #- ENABLE_JMX=true

      # System variables.
      - LOG_FILE=/opt/kotlin-app/logs/kotlin.log
      - JAVA_XMX=512m
      - JAVA_CPUS=1
      - TZ=America/Sao_Paulo

    volumes:
      - ./temp/:/tmp/
      - ./config/:/opt/kotlin-app/config/
      - ./logs/:/opt/kotlin-app/logs
